apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-apps2-pvc
spec:
  volumeName: nginx-apps2-pv  # Explicitly bind to 'my-pv'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"

